/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.example.stub;

public class ManufacturerElement {
	private _links _links;

 	public void set_links(_links _links) {
		this._links = _links;
	}

	public _links get_links() {
		return _links;
	}

	private java.lang.String startdate;

 	public void setStartdate(java.lang.String startdate) {
		this.startdate = startdate;
	}

	public java.lang.String getStartdate() {
		return startdate;
	}

	private java.lang.String name;

 	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getName() {
		return name;
	}

}