/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.example.stub;

public class _links {
	private Self self;

 	public void setSelf(Self self) {
		this.self = self;
	}

	public Self getSelf() {
		return self;
	}

	private Manufacturer manufacturer;

 	public void setManufacturer(Manufacturer manufacturer) {
		this.manufacturer = manufacturer;
	}

	public Manufacturer getManufacturer() {
		return manufacturer;
	}

}