/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.example.stub;

public class Self {
	private java.lang.String href;

 	public void setHref(java.lang.String href) {
		this.href = href;
	}

	public java.lang.String getHref() {
		return href;
	}

}