/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.example.stub;

public class _embedded {
	private ManufacturerElement[] manufacturers;

 	public void setManufacturers(ManufacturerElement[] manufacturers) {
		this.manufacturers = manufacturers;
	}

	public ManufacturerElement[] getManufacturers() {
		return manufacturers;
	}

}