/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.example.stub;

public class Response {
	private _embedded _embedded;

 	public void set_embedded(_embedded _embedded) {
		this._embedded = _embedded;
	}

	public _embedded get_embedded() {
		return _embedded;
	}

	private _links _links;

 	public void set_links(_links _links) {
		this._links = _links;
	}

	public _links get_links() {
		return _links;
	}

}